name = "eventsub-on-workers"
compatibility_date = "2023-12-01"

# [[migrations]]
# tag = "v1"
# new_classes = ["Counter"]

# [[durable_objects.bindings]]
# name = "COUNTER"
# class_name = "Counter"

# [vars]
# MY_VARIABLE = "production_value"

[[kv_namespaces]]
binding = "KV"
id = "71c95c2cd3354a6285bb8576f0a61fcf"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""
